apiVersion: kubeovn.io/v1
kind: Vpc
metadata:
  name: vpc-tenant-a
spec:
  vpcPeerings:
    - remoteVpc: vpc-tenant-b
      localConnectIP: 169.254.1.1/30
  staticRoutes:
    - cidr: 10.20.0.0/16
      nextHopIP: 169.254.1.2
      policy: policyDst
---
apiVersion: kubeovn.io/v1
kind: Vpc
metadata:
  name: vpc-tenant-b
spec:
  vpcPeerings:
    - remoteVpc: vpc-tenant-a
      localConnectIP: 169.254.1.2/30
  staticRoutes:
    - cidr: 10.10.0.0/16
      nextHopIP: 169.254.1.1
      policy: policyDst
