apiVersion: v1
kind: Pod
metadata:
  name: server-pod
  namespace: default
  labels:
    app: server-app
  annotations:
    ovn.kubernetes.io/logical_switch: subnet-tenant-b
spec:
  containers:
  - name: server
    image: alpine
    command: ["sh", "-c", "while true; do echo -e 'HTTP/1.1 200 OK\n\nhello from tenant-b' | nc -l -p 8080; done"]
    ports:
    - containerPort: 8080
      name: http
