apiVersion: v1
kind: Pod
metadata:
  name: no-egress-pod
  namespace: default
  annotations:
    ovn.kubernetes.io/logical_switch: subnet-no-egress
spec:
  containers:
    - name: alpine
      image: alpine:latest
      command:
        - sh
        - -c
        - "echo 'No-egress pod started successfully!'; tail -f /dev/null"
      resources:
        limits:
          cpu: "100m"
          memory: "64Mi"
        requests:
          cpu: "50m"
          memory: "32Mi"
  restartPolicy: Always
